version: '3.4'
services:
  mysql:
    container_name: project_d_mysql
    image: mysql:8.0.15
    command: --default-authentication-plugin=mysql_native_password --init-file=/data/mysql-init.sql
    restart: always
    ports:
      - "3306"
    volumes:
      - ../project-d-api/mysql-init.sql:/data/mysql-init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
  mongodb:
    container_name: project_d_mongodb
    image: mongo:4.0.6
    ports:
      - "27017"
  redis:
    container_name: project_d_redis
    image: redis:latest
    ports:
      - "6379"
  api:
    container_name: project_d_api
    depends_on:
      - mongodb
      - mysql
      - redis
    image: aehrt55/project-d-api:latest
    ports:
      - "3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/projectD
      - MYSQL_URI=mysql://root:mysql@mysql:3306/project_d
      - FACEBOOK_APP_ID=302560177128212
      - FACEBOOK_APP_SECRET=2027ad595a6f3cea53e3ea3cd357a546
  app:
    container_name: project_d_app
    image: aehrt55/project-d-app:latest
    ports:
      - "80"
  nginx:
    container_name: project_d_app_nginx
    depends_on:
      - app
    image: nginx
    ports:
      - 80:80
      - "443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./conf.d/default.conf.template:/etc/nginx/conf.d/default.conf.template
    environment:
      - API_PORT=3000
      - PORT=80
    command: /bin/bash -c "envsubst '$$PORT $$API_PORT' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
