# for development
version: '3.4'
services:
  mysql:
    container_name: project_d_app_mysql
    image: mysql:8.0.15
    command: --default-authentication-plugin=mysql_native_password --init-file=/data/mysql-init.sql
    restart: always
    ports:
      - "3306"
    volumes:
      - ../project-d-api/mysql-init.sql:/data/mysql-init.sql
      - ../project-d-api/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
  mongodb:
    container_name: project_d_app_mongodb
    image: mongo:4.0.6
    ports:
      - "27017"
    volumes:
      - ../project-d-api/mongodb:/data/db
  redis:
    container_name: project_d_app_redis
    image: redis:latest
    ports:
      - "6379"
  api:
    container_name: project_d_app_api
    depends_on:
      - mongodb
      - mysql
      - redis
    image: aehrt55/project-d-api:latest
    ports:
      - "3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/projectD
      - MYSQL_URI=mysql://root:mysql@mysql:3306/project_d
      - FACEBOOK_APP_ID=${FACEBOOK_APP_ID}
      - FACEBOOK_APP_SECRET=${FACEBOOK_APP_SECRET}
  app:
    container_name: project_d_app_nodejs
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - port=3000
    ports:
      - "3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./babel.config.js:/app/babel.config.js
      - ./.flowconfig:/app/.flowconfig
      - ./package.json:/app/package.json
    environment:
      - NODE_ENV=development
    command:
      - start
  nginx:
    container_name: project_d_app_nginx
    depends_on:
      - app
    image: nginx
    ports:
      - 80:80
      - "443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./conf.d/default.conf.template:/etc/nginx/conf.d/default.conf.template
    environment:
      - API_PORT=3000
      - PORT=3000
    command: /bin/bash -c "envsubst '$$PORT $$API_PORT' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
